---
- import_tasks: install.yml
  become: true
  tags: ['node_exporter', 'node_exporter:install']

- import_tasks: configure.yml
  become: true
  tags: ['node_exporter', 'node_exporter:configure']

- name: Ensure Node Exporter is enabled on boot
  become: true
  systemd:
    daemon_reload: true
    name: node_exporter
    enabled: true
    state: started
  tags: ['node_exporter', 'node_exporter:configure']
