---
sudo: required

env:
  - distribution: ubuntu
    version: xenial
    ansible: 2.4.3.0
  - distribution: ubuntu
    version: xenial
    ansible: 2.5.0rc3
  - distribution: ubuntu
    version: xenial
    ansible: 2.3.1.0
    
services:
  - docker

before_install:
  - 'sudo docker pull ${distribution}:${version}'
  - 'sudo docker build --no-cache --rm --file=travis/Dockerfile.${distribution}-${version} --build-arg ansible_version=${ansible} --tag=${distribution}-${version}-${ansible}:ansible travis'
  - 'sudo pip install yamllint'
  
script:
  - 'yamllint *'
  - container_id=$(mktemp)
  - 'sudo docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --volume="${PWD}":/etc/ansible/roles ${distribution}-${version}-${ansible}:ansible > "${container_id}"'
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/tests/test.yml --syntax-check'
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/tests/travis.yml'
  - >
    sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/tests/travis.yml
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
  - 'sudo docker rm -f "$(cat ${container_id})"'
